sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

script: jekyll build --destination _build

# branch whitelist, only for GitHub Pages
branches:
  only:
    - travisci-deploy     # test the gh-pages branch

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  provider: script
  local-dir: _build
  script: find . -type d \( -path "./.*" \) -prune -o -name "*" -print -exec curl --ftp-create-dirs -T {} ftp://hosting.subreg.cz/cloudnative.cz/ --user ${FTP_USER}:${FTP_PASS} \;
  skip-cleanup: true
  keep-history: true
  verbose: true
  on:
    branch: travisci-deploy