sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

script: jekyll build --destination _build

# branch whitelist, only for GitHub Pages
branches:
  only:
    - travisci-deploy     # test the gh-pages branch

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_deploy:
  - sudo apt-get update
  - sudo apt-get install wput -y

deploy:
  provider: script
  local-dir: _build
  script: wput --basename="./_build" -u ./_build/* ftp://${FTP_USER}:${FTP_PASS}@hosting.subreg.cz/cloudnative.cz/
  skip-cleanup: true
  keep-history: true
  verbose: true
  on:
    branch: travisci-deploy
